#!/bin/sh
#
# system control
#

start() {
	printf "Starting SystemControl: "
	mkdir -p /run/systemcontrol
	/usr/bin/systemcontrol &
	echo "OK"
}
stop() {
	printf "Stopping SystemControl: "
	killall systemcontrol
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

